'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace AbbConciseDocumentPrinting
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="AbbConciseDocumentPrintingSoap", [Namespace]:="http://www.abbconcise.com/")>  _
    Partial Public Class AbbConciseDocumentPrinting
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private AuthenticateUserOperationCompleted As System.Threading.SendOrPostCallback
        
        Private LoadAndRequestDocumentOperationCompleted As System.Threading.SendOrPostCallback
        
        Private LoadAndRequestDocumentObjectOperationCompleted As System.Threading.SendOrPostCallback
        
        Private LoadAndRequestDocumentObjectArrayOperationCompleted As System.Threading.SendOrPostCallback
        
        Private LogoutUserOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.WindowsApplication1.My.MySettings.Default.JsonClient_AbbConciseDocumentPrinting_AbbConciseDocumentPrinting
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event AuthenticateUserCompleted As AuthenticateUserCompletedEventHandler
        
        '''<remarks/>
        Public Event LoadAndRequestDocumentCompleted As LoadAndRequestDocumentCompletedEventHandler
        
        '''<remarks/>
        Public Event LoadAndRequestDocumentObjectCompleted As LoadAndRequestDocumentObjectCompletedEventHandler
        
        '''<remarks/>
        Public Event LoadAndRequestDocumentObjectArrayCompleted As LoadAndRequestDocumentObjectArrayCompletedEventHandler
        
        '''<remarks/>
        Public Event LogoutUserCompleted As LogoutUserCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.abbconcise.com/AuthenticateUser", RequestNamespace:="http://www.abbconcise.com/", ResponseNamespace:="http://www.abbconcise.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AuthenticateUser(ByVal UserID As String, ByVal Password As String) As AuthenticateResult
            Dim results() As Object = Me.Invoke("AuthenticateUser", New Object() {UserID, Password})
            Return CType(results(0),AuthenticateResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AuthenticateUserAsync(ByVal UserID As String, ByVal Password As String)
            Me.AuthenticateUserAsync(UserID, Password, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AuthenticateUserAsync(ByVal UserID As String, ByVal Password As String, ByVal userState As Object)
            If (Me.AuthenticateUserOperationCompleted Is Nothing) Then
                Me.AuthenticateUserOperationCompleted = AddressOf Me.OnAuthenticateUserOperationCompleted
            End If
            Me.InvokeAsync("AuthenticateUser", New Object() {UserID, Password}, Me.AuthenticateUserOperationCompleted, userState)
        End Sub
        
        Private Sub OnAuthenticateUserOperationCompleted(ByVal arg As Object)
            If (Not (Me.AuthenticateUserCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AuthenticateUserCompleted(Me, New AuthenticateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.abbconcise.com/LoadAndRequestDocument", RequestNamespace:="http://www.abbconcise.com/", ResponseNamespace:="http://www.abbconcise.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function LoadAndRequestDocument(ByVal AccessCode As String, ByVal RequestXML As System.Xml.XmlNode) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("LoadAndRequestDocument", New Object() {AccessCode, RequestXML})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LoadAndRequestDocumentAsync(ByVal AccessCode As String, ByVal RequestXML As System.Xml.XmlNode)
            Me.LoadAndRequestDocumentAsync(AccessCode, RequestXML, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LoadAndRequestDocumentAsync(ByVal AccessCode As String, ByVal RequestXML As System.Xml.XmlNode, ByVal userState As Object)
            If (Me.LoadAndRequestDocumentOperationCompleted Is Nothing) Then
                Me.LoadAndRequestDocumentOperationCompleted = AddressOf Me.OnLoadAndRequestDocumentOperationCompleted
            End If
            Me.InvokeAsync("LoadAndRequestDocument", New Object() {AccessCode, RequestXML}, Me.LoadAndRequestDocumentOperationCompleted, userState)
        End Sub
        
        Private Sub OnLoadAndRequestDocumentOperationCompleted(ByVal arg As Object)
            If (Not (Me.LoadAndRequestDocumentCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LoadAndRequestDocumentCompleted(Me, New LoadAndRequestDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.abbconcise.com/LoadAndRequestDocumentObject", RequestNamespace:="http://www.abbconcise.com/", ResponseNamespace:="http://www.abbconcise.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function LoadAndRequestDocumentObject(ByVal AccessCode As String, ByVal RequestInfo As DocumentPrintingRequestType) As DocumentPrintingResponseType
            Dim results() As Object = Me.Invoke("LoadAndRequestDocumentObject", New Object() {AccessCode, RequestInfo})
            Return CType(results(0),DocumentPrintingResponseType)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LoadAndRequestDocumentObjectAsync(ByVal AccessCode As String, ByVal RequestInfo As DocumentPrintingRequestType)
            Me.LoadAndRequestDocumentObjectAsync(AccessCode, RequestInfo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LoadAndRequestDocumentObjectAsync(ByVal AccessCode As String, ByVal RequestInfo As DocumentPrintingRequestType, ByVal userState As Object)
            If (Me.LoadAndRequestDocumentObjectOperationCompleted Is Nothing) Then
                Me.LoadAndRequestDocumentObjectOperationCompleted = AddressOf Me.OnLoadAndRequestDocumentObjectOperationCompleted
            End If
            Me.InvokeAsync("LoadAndRequestDocumentObject", New Object() {AccessCode, RequestInfo}, Me.LoadAndRequestDocumentObjectOperationCompleted, userState)
        End Sub
        
        Private Sub OnLoadAndRequestDocumentObjectOperationCompleted(ByVal arg As Object)
            If (Not (Me.LoadAndRequestDocumentObjectCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LoadAndRequestDocumentObjectCompleted(Me, New LoadAndRequestDocumentObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.abbconcise.com/LoadAndRequestDocumentObjectArray", RequestNamespace:="http://www.abbconcise.com/", ResponseNamespace:="http://www.abbconcise.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function LoadAndRequestDocumentObjectArray(ByVal AccessCode As String, ByVal RequestInfo() As DocumentPrintingRequestType) As DocumentPrintingResponseType
            Dim results() As Object = Me.Invoke("LoadAndRequestDocumentObjectArray", New Object() {AccessCode, RequestInfo})
            Return CType(results(0),DocumentPrintingResponseType)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LoadAndRequestDocumentObjectArrayAsync(ByVal AccessCode As String, ByVal RequestInfo() As DocumentPrintingRequestType)
            Me.LoadAndRequestDocumentObjectArrayAsync(AccessCode, RequestInfo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LoadAndRequestDocumentObjectArrayAsync(ByVal AccessCode As String, ByVal RequestInfo() As DocumentPrintingRequestType, ByVal userState As Object)
            If (Me.LoadAndRequestDocumentObjectArrayOperationCompleted Is Nothing) Then
                Me.LoadAndRequestDocumentObjectArrayOperationCompleted = AddressOf Me.OnLoadAndRequestDocumentObjectArrayOperationCompleted
            End If
            Me.InvokeAsync("LoadAndRequestDocumentObjectArray", New Object() {AccessCode, RequestInfo}, Me.LoadAndRequestDocumentObjectArrayOperationCompleted, userState)
        End Sub
        
        Private Sub OnLoadAndRequestDocumentObjectArrayOperationCompleted(ByVal arg As Object)
            If (Not (Me.LoadAndRequestDocumentObjectArrayCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LoadAndRequestDocumentObjectArrayCompleted(Me, New LoadAndRequestDocumentObjectArrayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.abbconcise.com/LogoutUser", RequestNamespace:="http://www.abbconcise.com/", ResponseNamespace:="http://www.abbconcise.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function LogoutUser(ByVal AccessCode As String) As LogoutUserResult
            Dim results() As Object = Me.Invoke("LogoutUser", New Object() {AccessCode})
            Return CType(results(0),LogoutUserResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LogoutUserAsync(ByVal AccessCode As String)
            Me.LogoutUserAsync(AccessCode, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LogoutUserAsync(ByVal AccessCode As String, ByVal userState As Object)
            If (Me.LogoutUserOperationCompleted Is Nothing) Then
                Me.LogoutUserOperationCompleted = AddressOf Me.OnLogoutUserOperationCompleted
            End If
            Me.InvokeAsync("LogoutUser", New Object() {AccessCode}, Me.LogoutUserOperationCompleted, userState)
        End Sub
        
        Private Sub OnLogoutUserOperationCompleted(ByVal arg As Object)
            If (Not (Me.LogoutUserCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LogoutUserCompleted(Me, New LogoutUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abbconcise.com/")>  _
    Partial Public Class AuthenticateResult
        
        Private responseField As CommonResult
        
        Private accessTokenField As String
        
        '''<remarks/>
        Public Property Response() As CommonResult
            Get
                Return Me.responseField
            End Get
            Set
                Me.responseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AccessToken() As String
            Get
                Return Me.accessTokenField
            End Get
            Set
                Me.accessTokenField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abbconcise.com/")>  _
    Partial Public Class CommonResult
        
        Private responseCodeField As Short
        
        Private messageField As String
        
        '''<remarks/>
        Public Property ResponseCode() As Short
            Get
                Return Me.responseCodeField
            End Get
            Set
                Me.responseCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abbconcise.com/")>  _
    Partial Public Class LogoutUserResult
        
        Private responseField As CommonResult
        
        '''<remarks/>
        Public Property Response() As CommonResult
            Get
                Return Me.responseField
            End Get
            Set
                Me.responseField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abbconcise.com/")>  _
    Partial Public Class DocumentPrintingResponseType
        
        Private responseCodeField As Short
        
        Private responseMessageField As String
        
        Private printRequestInfoField As PrintRequest
        
        Private responseDocumentTextField As String
        
        '''<remarks/>
        Public Property ResponseCode() As Short
            Get
                Return Me.responseCodeField
            End Get
            Set
                Me.responseCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ResponseMessage() As String
            Get
                Return Me.responseMessageField
            End Get
            Set
                Me.responseMessageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PrintRequestInfo() As PrintRequest
            Get
                Return Me.printRequestInfoField
            End Get
            Set
                Me.printRequestInfoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ResponseDocumentText() As String
            Get
                Return Me.responseDocumentTextField
            End Get
            Set
                Me.responseDocumentTextField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abbconcise.com/")>  _
    Partial Public Class PrintRequest
        
        Private requestTypeField As String
        
        Private reportNameField As String
        
        Private printerIpField As String
        
        Private returnPDFField As Boolean
        
        '''<remarks/>
        Public Property RequestType() As String
            Get
                Return Me.requestTypeField
            End Get
            Set
                Me.requestTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ReportName() As String
            Get
                Return Me.reportNameField
            End Get
            Set
                Me.reportNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PrinterIp() As String
            Get
                Return Me.printerIpField
            End Get
            Set
                Me.printerIpField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ReturnPDF() As Boolean
            Get
                Return Me.returnPDFField
            End Get
            Set
                Me.returnPDFField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abbconcise.com/")>  _
    Partial Public Class InvoiceNotes
        
        Private sequenceNoField As Short
        
        Private noteCodeField As String
        
        Private noteTextField As String
        
        '''<remarks/>
        Public Property SequenceNo() As Short
            Get
                Return Me.sequenceNoField
            End Get
            Set
                Me.sequenceNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NoteCode() As String
            Get
                Return Me.noteCodeField
            End Get
            Set
                Me.noteCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NoteText() As String
            Get
                Return Me.noteTextField
            End Get
            Set
                Me.noteTextField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abbconcise.com/")>  _
    Partial Public Class InvoiceLensBankSummary
        
        Private sequenceNoField As Short
        
        Private descriptionField As String
        
        '''<remarks/>
        Public Property SequenceNo() As Short
            Get
                Return Me.sequenceNoField
            End Get
            Set
                Me.sequenceNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abbconcise.com/")>  _
    Partial Public Class Address
        
        Private addressTypeField As AddressTypes
        
        Private nameField As String
        
        Private name2Field As String
        
        Private contactField As String
        
        Private phoneNumberField As String
        
        Private faxNumberField As String
        
        Private addressLine1Field As String
        
        Private addressLine2Field As String
        
        Private addressLine3Field As String
        
        Private cityField As String
        
        Private stateProvinceCodeField As String
        
        Private postalCodeField As String
        
        Private countryCodeField As String
        
        Private emailAddressField As String
        
        '''<remarks/>
        Public Property AddressType() As AddressTypes
            Get
                Return Me.addressTypeField
            End Get
            Set
                Me.addressTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Name2() As String
            Get
                Return Me.name2Field
            End Get
            Set
                Me.name2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Contact() As String
            Get
                Return Me.contactField
            End Get
            Set
                Me.contactField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PhoneNumber() As String
            Get
                Return Me.phoneNumberField
            End Get
            Set
                Me.phoneNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FaxNumber() As String
            Get
                Return Me.faxNumberField
            End Get
            Set
                Me.faxNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AddressLine1() As String
            Get
                Return Me.addressLine1Field
            End Get
            Set
                Me.addressLine1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AddressLine2() As String
            Get
                Return Me.addressLine2Field
            End Get
            Set
                Me.addressLine2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AddressLine3() As String
            Get
                Return Me.addressLine3Field
            End Get
            Set
                Me.addressLine3Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property City() As String
            Get
                Return Me.cityField
            End Get
            Set
                Me.cityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StateProvinceCode() As String
            Get
                Return Me.stateProvinceCodeField
            End Get
            Set
                Me.stateProvinceCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PostalCode() As String
            Get
                Return Me.postalCodeField
            End Get
            Set
                Me.postalCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CountryCode() As String
            Get
                Return Me.countryCodeField
            End Get
            Set
                Me.countryCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EmailAddress() As String
            Get
                Return Me.emailAddressField
            End Get
            Set
                Me.emailAddressField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abbconcise.com/")>  _
    Public Enum AddressTypes
        
        '''<remarks/>
        BillTo
        
        '''<remarks/>
        ReturnTo
        
        '''<remarks/>
        ShipFrom
        
        '''<remarks/>
        ShipTo
        
        '''<remarks/>
        Office
        
        '''<remarks/>
        BillingOffice
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abbconcise.com/")>  _
    Partial Public Class InvoiceDetailAddon
        
        Private sequenceNoField As Integer
        
        Private addonDescriptionField As String
        
        Private addonAmountField As Double
        
        '''<remarks/>
        Public Property SequenceNo() As Integer
            Get
                Return Me.sequenceNoField
            End Get
            Set
                Me.sequenceNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AddonDescription() As String
            Get
                Return Me.addonDescriptionField
            End Get
            Set
                Me.addonDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AddonAmount() As Double
            Get
                Return Me.addonAmountField
            End Get
            Set
                Me.addonAmountField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abbconcise.com/")>  _
    Partial Public Class InvoiceDetails
        
        Private invoiceLnoField As Short
        
        Private itemCodeField As String
        
        Private itemDescriptionField As String
        
        Private itemDescription2Field As String
        
        Private webItemDescriptionField As String
        
        Private itemBinLocationField As String
        
        Private orderGroupField As String
        
        Private patientNameField As String
        
        Private patientReferenceField As String
        
        Private leftRightIndicatorField As String
        
        Private quantityOrderedField As Integer
        
        Private quantityShippedField As Integer
        
        Private quantityDueField As Integer
        
        Private baseCurveField As String
        
        Private diameterField As String
        
        Private spherePowerField As String
        
        Private cylinderField As String
        
        Private axisField As String
        
        Private colorField As String
        
        Private addPowerField As String
        
        Private unitPriceField As Decimal
        
        Private patientPriceField As Decimal
        
        Private extendedPriceField As Decimal
        
        Private patientExtendedPriceField As Decimal
        
        Private salesCategoryField As String
        
        Private etaInfoField As String
        
        Private detailAddonsField() As InvoiceDetailAddon
        
        '''<remarks/>
        Public Property InvoiceLno() As Short
            Get
                Return Me.invoiceLnoField
            End Get
            Set
                Me.invoiceLnoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ItemCode() As String
            Get
                Return Me.itemCodeField
            End Get
            Set
                Me.itemCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ItemDescription() As String
            Get
                Return Me.itemDescriptionField
            End Get
            Set
                Me.itemDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ItemDescription2() As String
            Get
                Return Me.itemDescription2Field
            End Get
            Set
                Me.itemDescription2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property WebItemDescription() As String
            Get
                Return Me.webItemDescriptionField
            End Get
            Set
                Me.webItemDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ItemBinLocation() As String
            Get
                Return Me.itemBinLocationField
            End Get
            Set
                Me.itemBinLocationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OrderGroup() As String
            Get
                Return Me.orderGroupField
            End Get
            Set
                Me.orderGroupField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PatientName() As String
            Get
                Return Me.patientNameField
            End Get
            Set
                Me.patientNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PatientReference() As String
            Get
                Return Me.patientReferenceField
            End Get
            Set
                Me.patientReferenceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LeftRightIndicator() As String
            Get
                Return Me.leftRightIndicatorField
            End Get
            Set
                Me.leftRightIndicatorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property QuantityOrdered() As Integer
            Get
                Return Me.quantityOrderedField
            End Get
            Set
                Me.quantityOrderedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property QuantityShipped() As Integer
            Get
                Return Me.quantityShippedField
            End Get
            Set
                Me.quantityShippedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property QuantityDue() As Integer
            Get
                Return Me.quantityDueField
            End Get
            Set
                Me.quantityDueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BaseCurve() As String
            Get
                Return Me.baseCurveField
            End Get
            Set
                Me.baseCurveField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Diameter() As String
            Get
                Return Me.diameterField
            End Get
            Set
                Me.diameterField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SpherePower() As String
            Get
                Return Me.spherePowerField
            End Get
            Set
                Me.spherePowerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cylinder() As String
            Get
                Return Me.cylinderField
            End Get
            Set
                Me.cylinderField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Axis() As String
            Get
                Return Me.axisField
            End Get
            Set
                Me.axisField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Color() As String
            Get
                Return Me.colorField
            End Get
            Set
                Me.colorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AddPower() As String
            Get
                Return Me.addPowerField
            End Get
            Set
                Me.addPowerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UnitPrice() As Decimal
            Get
                Return Me.unitPriceField
            End Get
            Set
                Me.unitPriceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PatientPrice() As Decimal
            Get
                Return Me.patientPriceField
            End Get
            Set
                Me.patientPriceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ExtendedPrice() As Decimal
            Get
                Return Me.extendedPriceField
            End Get
            Set
                Me.extendedPriceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PatientExtendedPrice() As Decimal
            Get
                Return Me.patientExtendedPriceField
            End Get
            Set
                Me.patientExtendedPriceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SalesCategory() As String
            Get
                Return Me.salesCategoryField
            End Get
            Set
                Me.salesCategoryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EtaInfo() As String
            Get
                Return Me.etaInfoField
            End Get
            Set
                Me.etaInfoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DetailAddons() As InvoiceDetailAddon()
            Get
                Return Me.detailAddonsField
            End Get
            Set
                Me.detailAddonsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abbconcise.com/")>  _
    Partial Public Class InvoiceHeaderCharges
        
        Private sequenceNoField As Integer
        
        Private chargeDescriptionField As String
        
        Private chargeAmountField As Double
        
        Private isSubTotalDividerField As String
        
        '''<remarks/>
        Public Property SequenceNo() As Integer
            Get
                Return Me.sequenceNoField
            End Get
            Set
                Me.sequenceNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ChargeDescription() As String
            Get
                Return Me.chargeDescriptionField
            End Get
            Set
                Me.chargeDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ChargeAmount() As Double
            Get
                Return Me.chargeAmountField
            End Get
            Set
                Me.chargeAmountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property isSubTotalDivider() As String
            Get
                Return Me.isSubTotalDividerField
            End Get
            Set
                Me.isSubTotalDividerField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abbconcise.com/")>  _
    Partial Public Class InvoiceHeader
        
        Private invoiceTypeField As String
        
        Private invoiceNoField As String
        
        Private invoiceDateField As String
        
        Private customerNoField As String
        
        Private shipToNoField As String
        
        Private billToAccountField As String
        
        Private providerNumberField As String
        
        Private orderNoField As String
        
        Private orderDateField As String
        
        Private orderTimeField As String
        
        Private invoicePrintDateField As String
        
        Private webOrderNoField As String
        
        Private customerPONumberField As String
        
        Private salesRepCodeField As String
        
        Private customerOrderIDField As String
        
        Private customerIDField As String
        
        Private carrierField As String
        
        Private shipViaField As String
        
        Private shipMethodDescriptionField As String
        
        Private shipMethodWebDescriptionField As String
        
        Private shipmentTrackingInfoField As String
        
        Private termsDescriptionField As String
        
        Private orderCommentField As String
        
        Private orderByCallerNameField As String
        
        Private orderTakenByField As String
        
        Private orderSourceField As String
        
        Private partnerOrderOriginField As String
        
        Private merchandiseTotalField As Decimal
        
        Private invoiceSalesTaxField As Decimal
        
        Private invoiceFreightField As Decimal
        
        Private invoiceMiscSalesField As Decimal
        
        Private invoiceTotalSalesField As Decimal
        
        Private packSlipSalesTaxField As Decimal
        
        Private packSlipFreightField As Decimal
        
        Private packSlipFuelSurchargeField As Decimal
        
        Private packSlipTotalField As Decimal
        
        Private packSlipNotesField As String
        
        Private shipToPatientField As String
        
        Private patientIDField As String
        
        Private patientInvoiceSalesField As Decimal
        
        Private patientSalesTaxField As Decimal
        
        Private patientFreightField As Decimal
        
        Private patientTotalSalesField As Decimal
        
        Private patientDiscountField As Decimal
        
        Private patientDifferenceField As Decimal
        
        Private importedPatientInvoiceSalesField As Decimal
        
        Private importedPatientSalesTaxField As Decimal
        
        Private importedPatientFreightField As Decimal
        
        Private importedPatientTotalSalesField As Decimal
        
        Private importedPatientDiscountField As Decimal
        
        Private importedPatientCopayField As Decimal
        
        Private isReprintField As String
        
        Private promoCodeField As String
        
        Private transmissionDateField As String
        
        Private officeWebSiteField As String
        
        Private paymentMethodField As String
        
        Private prescribingDoctorField As String
        
        Private rebateTextField As String
        
        Private headerBodyTextField As String
        
        Private shipmentNumberField As String
        
        Private ediReferenceNumberField As String
        
        Private wDSIIInvoiceNumberField As String
        
        Private displayPricingField As String
        
        Private pageFooterTextField As String
        
        Private thirdPartyOrderNumberField As String
        
        Private thirdPartyOrderDateField As String
        
        Private thirdPartyBillToAccountField As String
        
        Private thirdPartyShipToAccountField As String
        
        Private thirdPartyPONumberField As String
        
        Private thirdPartyInvoiceNumberField As String
        
        Private thirdPartyTermsDescriptionField As String
        
        Private thirdPartyCarrierCodeField As String
        
        Private thirdPartyShipVIaCodeField As String
        
        Private shipCompleteField As String
        
        Private invoiceChargesField() As InvoiceHeaderCharges
        
        Private invoiceDetailsField() As InvoiceDetails
        
        Private invoiceAddressesField() As Address
        
        Private invoiceLensBankSummaryField() As InvoiceLensBankSummary
        
        Private invoiceNotesField() As InvoiceNotes
        
        '''<remarks/>
        Public Property InvoiceType() As String
            Get
                Return Me.invoiceTypeField
            End Get
            Set
                Me.invoiceTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InvoiceNo() As String
            Get
                Return Me.invoiceNoField
            End Get
            Set
                Me.invoiceNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InvoiceDate() As String
            Get
                Return Me.invoiceDateField
            End Get
            Set
                Me.invoiceDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CustomerNo() As String
            Get
                Return Me.customerNoField
            End Get
            Set
                Me.customerNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ShipToNo() As String
            Get
                Return Me.shipToNoField
            End Get
            Set
                Me.shipToNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BillToAccount() As String
            Get
                Return Me.billToAccountField
            End Get
            Set
                Me.billToAccountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ProviderNumber() As String
            Get
                Return Me.providerNumberField
            End Get
            Set
                Me.providerNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OrderNo() As String
            Get
                Return Me.orderNoField
            End Get
            Set
                Me.orderNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OrderDate() As String
            Get
                Return Me.orderDateField
            End Get
            Set
                Me.orderDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OrderTime() As String
            Get
                Return Me.orderTimeField
            End Get
            Set
                Me.orderTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InvoicePrintDate() As String
            Get
                Return Me.invoicePrintDateField
            End Get
            Set
                Me.invoicePrintDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property WebOrderNo() As String
            Get
                Return Me.webOrderNoField
            End Get
            Set
                Me.webOrderNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CustomerPONumber() As String
            Get
                Return Me.customerPONumberField
            End Get
            Set
                Me.customerPONumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SalesRepCode() As String
            Get
                Return Me.salesRepCodeField
            End Get
            Set
                Me.salesRepCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CustomerOrderID() As String
            Get
                Return Me.customerOrderIDField
            End Get
            Set
                Me.customerOrderIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CustomerID() As String
            Get
                Return Me.customerIDField
            End Get
            Set
                Me.customerIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Carrier() As String
            Get
                Return Me.carrierField
            End Get
            Set
                Me.carrierField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ShipVia() As String
            Get
                Return Me.shipViaField
            End Get
            Set
                Me.shipViaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ShipMethodDescription() As String
            Get
                Return Me.shipMethodDescriptionField
            End Get
            Set
                Me.shipMethodDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ShipMethodWebDescription() As String
            Get
                Return Me.shipMethodWebDescriptionField
            End Get
            Set
                Me.shipMethodWebDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ShipmentTrackingInfo() As String
            Get
                Return Me.shipmentTrackingInfoField
            End Get
            Set
                Me.shipmentTrackingInfoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TermsDescription() As String
            Get
                Return Me.termsDescriptionField
            End Get
            Set
                Me.termsDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OrderComment() As String
            Get
                Return Me.orderCommentField
            End Get
            Set
                Me.orderCommentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OrderByCallerName() As String
            Get
                Return Me.orderByCallerNameField
            End Get
            Set
                Me.orderByCallerNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OrderTakenBy() As String
            Get
                Return Me.orderTakenByField
            End Get
            Set
                Me.orderTakenByField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OrderSource() As String
            Get
                Return Me.orderSourceField
            End Get
            Set
                Me.orderSourceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PartnerOrderOrigin() As String
            Get
                Return Me.partnerOrderOriginField
            End Get
            Set
                Me.partnerOrderOriginField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MerchandiseTotal() As Decimal
            Get
                Return Me.merchandiseTotalField
            End Get
            Set
                Me.merchandiseTotalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InvoiceSalesTax() As Decimal
            Get
                Return Me.invoiceSalesTaxField
            End Get
            Set
                Me.invoiceSalesTaxField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InvoiceFreight() As Decimal
            Get
                Return Me.invoiceFreightField
            End Get
            Set
                Me.invoiceFreightField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InvoiceMiscSales() As Decimal
            Get
                Return Me.invoiceMiscSalesField
            End Get
            Set
                Me.invoiceMiscSalesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InvoiceTotalSales() As Decimal
            Get
                Return Me.invoiceTotalSalesField
            End Get
            Set
                Me.invoiceTotalSalesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PackSlipSalesTax() As Decimal
            Get
                Return Me.packSlipSalesTaxField
            End Get
            Set
                Me.packSlipSalesTaxField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PackSlipFreight() As Decimal
            Get
                Return Me.packSlipFreightField
            End Get
            Set
                Me.packSlipFreightField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PackSlipFuelSurcharge() As Decimal
            Get
                Return Me.packSlipFuelSurchargeField
            End Get
            Set
                Me.packSlipFuelSurchargeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PackSlipTotal() As Decimal
            Get
                Return Me.packSlipTotalField
            End Get
            Set
                Me.packSlipTotalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PackSlipNotes() As String
            Get
                Return Me.packSlipNotesField
            End Get
            Set
                Me.packSlipNotesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ShipToPatient() As String
            Get
                Return Me.shipToPatientField
            End Get
            Set
                Me.shipToPatientField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PatientID() As String
            Get
                Return Me.patientIDField
            End Get
            Set
                Me.patientIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PatientInvoiceSales() As Decimal
            Get
                Return Me.patientInvoiceSalesField
            End Get
            Set
                Me.patientInvoiceSalesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PatientSalesTax() As Decimal
            Get
                Return Me.patientSalesTaxField
            End Get
            Set
                Me.patientSalesTaxField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PatientFreight() As Decimal
            Get
                Return Me.patientFreightField
            End Get
            Set
                Me.patientFreightField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PatientTotalSales() As Decimal
            Get
                Return Me.patientTotalSalesField
            End Get
            Set
                Me.patientTotalSalesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PatientDiscount() As Decimal
            Get
                Return Me.patientDiscountField
            End Get
            Set
                Me.patientDiscountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PatientDifference() As Decimal
            Get
                Return Me.patientDifferenceField
            End Get
            Set
                Me.patientDifferenceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ImportedPatientInvoiceSales() As Decimal
            Get
                Return Me.importedPatientInvoiceSalesField
            End Get
            Set
                Me.importedPatientInvoiceSalesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ImportedPatientSalesTax() As Decimal
            Get
                Return Me.importedPatientSalesTaxField
            End Get
            Set
                Me.importedPatientSalesTaxField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ImportedPatientFreight() As Decimal
            Get
                Return Me.importedPatientFreightField
            End Get
            Set
                Me.importedPatientFreightField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ImportedPatientTotalSales() As Decimal
            Get
                Return Me.importedPatientTotalSalesField
            End Get
            Set
                Me.importedPatientTotalSalesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ImportedPatientDiscount() As Decimal
            Get
                Return Me.importedPatientDiscountField
            End Get
            Set
                Me.importedPatientDiscountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ImportedPatientCopay() As Decimal
            Get
                Return Me.importedPatientCopayField
            End Get
            Set
                Me.importedPatientCopayField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsReprint() As String
            Get
                Return Me.isReprintField
            End Get
            Set
                Me.isReprintField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PromoCode() As String
            Get
                Return Me.promoCodeField
            End Get
            Set
                Me.promoCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TransmissionDate() As String
            Get
                Return Me.transmissionDateField
            End Get
            Set
                Me.transmissionDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OfficeWebSite() As String
            Get
                Return Me.officeWebSiteField
            End Get
            Set
                Me.officeWebSiteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PaymentMethod() As String
            Get
                Return Me.paymentMethodField
            End Get
            Set
                Me.paymentMethodField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PrescribingDoctor() As String
            Get
                Return Me.prescribingDoctorField
            End Get
            Set
                Me.prescribingDoctorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RebateText() As String
            Get
                Return Me.rebateTextField
            End Get
            Set
                Me.rebateTextField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HeaderBodyText() As String
            Get
                Return Me.headerBodyTextField
            End Get
            Set
                Me.headerBodyTextField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ShipmentNumber() As String
            Get
                Return Me.shipmentNumberField
            End Get
            Set
                Me.shipmentNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EdiReferenceNumber() As String
            Get
                Return Me.ediReferenceNumberField
            End Get
            Set
                Me.ediReferenceNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property WDSIIInvoiceNumber() As String
            Get
                Return Me.wDSIIInvoiceNumberField
            End Get
            Set
                Me.wDSIIInvoiceNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DisplayPricing() As String
            Get
                Return Me.displayPricingField
            End Get
            Set
                Me.displayPricingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PageFooterText() As String
            Get
                Return Me.pageFooterTextField
            End Get
            Set
                Me.pageFooterTextField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ThirdPartyOrderNumber() As String
            Get
                Return Me.thirdPartyOrderNumberField
            End Get
            Set
                Me.thirdPartyOrderNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ThirdPartyOrderDate() As String
            Get
                Return Me.thirdPartyOrderDateField
            End Get
            Set
                Me.thirdPartyOrderDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ThirdPartyBillToAccount() As String
            Get
                Return Me.thirdPartyBillToAccountField
            End Get
            Set
                Me.thirdPartyBillToAccountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ThirdPartyShipToAccount() As String
            Get
                Return Me.thirdPartyShipToAccountField
            End Get
            Set
                Me.thirdPartyShipToAccountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ThirdPartyPONumber() As String
            Get
                Return Me.thirdPartyPONumberField
            End Get
            Set
                Me.thirdPartyPONumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ThirdPartyInvoiceNumber() As String
            Get
                Return Me.thirdPartyInvoiceNumberField
            End Get
            Set
                Me.thirdPartyInvoiceNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ThirdPartyTermsDescription() As String
            Get
                Return Me.thirdPartyTermsDescriptionField
            End Get
            Set
                Me.thirdPartyTermsDescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ThirdPartyCarrierCode() As String
            Get
                Return Me.thirdPartyCarrierCodeField
            End Get
            Set
                Me.thirdPartyCarrierCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ThirdPartyShipVIaCode() As String
            Get
                Return Me.thirdPartyShipVIaCodeField
            End Get
            Set
                Me.thirdPartyShipVIaCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ShipComplete() As String
            Get
                Return Me.shipCompleteField
            End Get
            Set
                Me.shipCompleteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InvoiceCharges() As InvoiceHeaderCharges()
            Get
                Return Me.invoiceChargesField
            End Get
            Set
                Me.invoiceChargesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InvoiceDetails() As InvoiceDetails()
            Get
                Return Me.invoiceDetailsField
            End Get
            Set
                Me.invoiceDetailsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InvoiceAddresses() As Address()
            Get
                Return Me.invoiceAddressesField
            End Get
            Set
                Me.invoiceAddressesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InvoiceLensBankSummary() As InvoiceLensBankSummary()
            Get
                Return Me.invoiceLensBankSummaryField
            End Get
            Set
                Me.invoiceLensBankSummaryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InvoiceNotes() As InvoiceNotes()
            Get
                Return Me.invoiceNotesField
            End Get
            Set
                Me.invoiceNotesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.abbconcise.com/")>  _
    Partial Public Class DocumentPrintingRequestType
        
        Private printRequestInfoField As PrintRequest
        
        Private documentHeaderField() As InvoiceHeader
        
        '''<remarks/>
        Public Property PrintRequestInfo() As PrintRequest
            Get
                Return Me.printRequestInfoField
            End Get
            Set
                Me.printRequestInfoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DocumentHeader() As InvoiceHeader()
            Get
                Return Me.documentHeaderField
            End Get
            Set
                Me.documentHeaderField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub AuthenticateUserCompletedEventHandler(ByVal sender As Object, ByVal e As AuthenticateUserCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AuthenticateUserCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As AuthenticateResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),AuthenticateResult)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub LoadAndRequestDocumentCompletedEventHandler(ByVal sender As Object, ByVal e As LoadAndRequestDocumentCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LoadAndRequestDocumentCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Xml.XmlNode
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Xml.XmlNode)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub LoadAndRequestDocumentObjectCompletedEventHandler(ByVal sender As Object, ByVal e As LoadAndRequestDocumentObjectCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LoadAndRequestDocumentObjectCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DocumentPrintingResponseType
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DocumentPrintingResponseType)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub LoadAndRequestDocumentObjectArrayCompletedEventHandler(ByVal sender As Object, ByVal e As LoadAndRequestDocumentObjectArrayCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LoadAndRequestDocumentObjectArrayCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DocumentPrintingResponseType
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DocumentPrintingResponseType)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub LogoutUserCompletedEventHandler(ByVal sender As Object, ByVal e As LogoutUserCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LogoutUserCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As LogoutUserResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),LogoutUserResult)
            End Get
        End Property
    End Class
End Namespace
